// <auto-generated />
namespace _08_OneToMany.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class createshopdb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createshopdb));
        
        string IMigrationMetadata.Id
        {
            get { return "201908311400327_create shop db"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
