// <auto-generated />
namespace _08_CodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Deleteaddresstable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Deleteaddresstable));
        
        string IMigrationMetadata.Id
        {
            get { return "201908311201556_Delete address table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
